# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260e128766fa8406da449ef5d13352905d9ae4456d7560079c0194e87651ac0a9898da5abcbb925e0a081cbc1f9c8738803e40a738311aeae46c188077b17599

test:
  secret_key_base: 5b85288907ab89e5e8d442534c2107390b4e30cedbb7abb97414f13853d2290ef344756938a2bea5ce96ab9972654593d6ed4ee46c979b48ee45f0b7fdec980a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
